### ISSUE TITLE
Basic Win Area Does Not Work

### ISSUE THREAD

**Issue by galax-sci** [ArokhSlade/Brackeys-Jam-2024-2-The-6-Tuplets#43]
## Describe the bug
When you enter the area meant to have you "win the game" (as it's a debug build, there's no actual game play to win at), nothing happens. 

## To Reproduce
Walk into the game win area. See it doesn't work. Cry.

## Expected behavior
When you walk into the designated winning area, you should be sent to the winning screen.

## Additional context
Adding a print call identifies that the issue seems to be with the call to _on_area_3d_body_entered(_body). It's unable to register the body being entered.

**Comment by ArokhSlade** [comment]
was fixed recently.
